# Generated by Django 4.0.4 on 2022-05-06 02:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_articles_author_alter_articles_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
