# Generated by Django 4.0.4 on 2022-05-07 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_alter_articles_options_articles_publish_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={},
        ),
        migrations.RemoveField(
            model_name='articles',
            name='publish',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='status',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='updated',
        ),
    ]
